// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Exam_Form.Models
{
    public partial class GenerateExamResult
    {
        public int Question_Id { get; set; }
        public string Question_Head { get; set; }
        public string Question_Type { get; set; }
        public string Question_Answer { get; set; }
        public int Question_Points { get; set; }
        public int Course_Id { get; set; }
    }
}
