// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Exam_Form.Models
{
    public partial class GenerateExamThenInsertItResult
    {
        public int? Question_Id { get; set; }
        public string Question_Head { get; set; }
        public string Question_Type { get; set; }
    }
}
