// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Exam_Form.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Exam_Form.Models
{
    public partial interface IExamination_Sys_ContextProcedures
    {
        Task<List<CorrectExamResult>> CorrectExamAsync(int? Student_Id, int? Exam_Id, DataTable Answers, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GenerateExamResult>> GenerateExamAsync(int? Course_Id, int? Num_Questions, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GenerateExamThenInsertItResult>> GenerateExamThenInsertItAsync(int? Course_Id, int? Student_Id, int? Exam_Id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetStudentCoursesAndExamsResult>> GetStudentCoursesAndExamsAsync(int? StudentId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> InsertStudentAnswerAsync(int? Student_Id, int? Exam_Id, int? Question_Id, string Student_Ans, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
